arch:
  - amd64
  - ppc64le

#language: perl
sudo: required
script:
  - \curl -L http://install.perlbrew.pl | sudo bash
  - source ~/perl5/perlbrew/etc/bashrc
  - curl -L http://cpanmin.us | perl - --sudo App::cpanminus
  - perl --version
  - sudo apt install strace -y
  - sudo strace - c cpanm --help         # get help
  - cpanm URI            # install the URI module from CPAN
  - cpanm --version
